stages:
  - test
  - build

default:
  image: golang:1.23

unit-test:
  stage: test
  script:
    - go test ./...

build-arm-ecu:
  stage: build
  script:
    - make build-arm
  artifacts:
    paths:
      - build/guest/body-ecu
    expire_in: 1 week
